#############################################################################
# Makefile for building ./zenkaku
# Generated by tmake at 10:08, 2006/09/13
#     Project: zenkaku
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -Wall -W -O2 -DNO_DEBUG
CXXFLAGS=	-pipe -DQT_QWS_EBX -DQT_QWS_CUSTOM -DQWS -fno-exceptions -fno-rtti -fsigned-char -DQT_NO_DRAGANDDROP -DQT_NO_PROPERTIES -Wall -W -O2 -DNO_DEBUG
INCPATH	=	-I/usr/local/zgcc34/include -Iinclude -I$(QTDIR)/include
LINK	=	g++
LFLAGS	=	
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -Llib -lncursesj
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	CDate.h \
		CHashTable.h \
		CString.h \
		Config.h \
		Data.h \
		File.h \
		Game.h \
		Hash.h \
		Title.h \
		WinEditValue.h \
		WinEditValue_Cmask.h \
		WinEditValue_Event.h \
		WinEditValue_Flg.h \
		WinEditValue_Pos.h \
		WinEditValue_Tile.h \
		WinEnemyEditor.h \
		WinEventEditor.h \
		WinGetPath.h \
		WinItemEditor.h \
		WinMapEditor.h \
		WinMessageEditor.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinPGEditor.h \
		WinPartyEditor.h \
		WinScenarioEditor.h \
		WinSelect1Icon.h \
		WinSelect1Item.h \
		WinSelect1Line.h \
		WinShopEditor.h \
		WinTitle.h \
		Windows.h \
		common.h \
		main.h \
		msg.h \
		win.h
SOURCES =	CDate.cpp \
		CString.cpp \
		CString_st.cpp \
		CString_stin.cpp \
		Config.cpp \
		Data.cpp \
		File.cpp \
		Game.cpp \
		Hash.cpp \
		Title.cpp \
		WinEditValue.cpp \
		WinEditValue_Cmask.cpp \
		WinEditValue_Event.cpp \
		WinEditValue_Flg.cpp \
		WinEditValue_Pos.cpp \
		WinEditValue_Tile.cpp \
		WinEnemyEditor.cpp \
		WinEventEditor.cpp \
		WinGetPath.cpp \
		WinItemEditor.cpp \
		WinMapEditor.cpp \
		WinMessageEditor.cpp \
		WinMsg.cpp \
		WinMycharEditor.cpp \
		WinPGEditor.cpp \
		WinPartyEditor.cpp \
		WinScenarioEditor.cpp \
		WinSelect1Icon.cpp \
		WinSelect1Item.cpp \
		WinSelect1Line.cpp \
		WinShopEditor.cpp \
		WinTitle.cpp \
		Windows.cpp \
		main.cpp
OBJECTS =	CDate.o \
		CString.o \
		CString_st.o \
		CString_stin.o \
		Config.o \
		Data.o \
		File.o \
		Game.o \
		Hash.o \
		Title.o \
		WinEditValue.o \
		WinEditValue_Cmask.o \
		WinEditValue_Event.o \
		WinEditValue_Flg.o \
		WinEditValue_Pos.o \
		WinEditValue_Tile.o \
		WinEnemyEditor.o \
		WinEventEditor.o \
		WinGetPath.o \
		WinItemEditor.o \
		WinMapEditor.o \
		WinMessageEditor.o \
		WinMsg.o \
		WinMycharEditor.o \
		WinPGEditor.o \
		WinPartyEditor.o \
		WinScenarioEditor.o \
		WinSelect1Icon.o \
		WinSelect1Item.o \
		WinSelect1Line.o \
		WinShopEditor.o \
		WinTitle.o \
		Windows.o \
		main.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	./zenkaku
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: Makefile

Makefile: zenkaku.pro
	tmake zenkaku.pro -o Makefile

dist:
	$(TAR) zenkaku.tar zenkaku.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) zenkaku.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

CDate.o: CDate.cpp \
		CDate.h

CString.o: CString.cpp \
		CString.h

CString_st.o: CString_st.cpp \
		CString.h

CString_stin.o: CString_stin.cpp \
		CString.h

Config.o: Config.cpp \
		Config.h \
		include/curses.h

Data.o: Data.cpp \
		Data.h \
		include/curses.h \
		common.h \
		CString.h

File.o: File.cpp \
		File.h \
		CString.h \
		Config.h \
		include/curses.h \
		win.h \
		WinTitle.h \
		Windows.h \
		common.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

Game.o: Game.cpp \
		Game.h \
		include/curses.h \
		common.h \
		CString.h \
		Config.h

Hash.o: Hash.cpp \
		Hash.h

Title.o: Title.cpp \
		Title.h \
		include/curses.h \
		common.h \
		CString.h \
		win.h \
		WinTitle.h \
		Windows.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEditValue.o: WinEditValue.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEditValue_Cmask.o: WinEditValue_Cmask.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEditValue_Event.o: WinEditValue_Event.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEditValue_Flg.o: WinEditValue_Flg.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEditValue_Pos.o: WinEditValue_Pos.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEditValue_Tile.o: WinEditValue_Tile.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEnemyEditor.o: WinEnemyEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinEventEditor.o: WinEventEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinGetPath.o: WinGetPath.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinItemEditor.o: WinItemEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinMapEditor.o: WinMapEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinMessageEditor.o: WinMessageEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinMsg.o: WinMsg.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinMycharEditor.o: WinMycharEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinPGEditor.o: WinPGEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinPartyEditor.o: WinPartyEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinScenarioEditor.o: WinScenarioEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinSelect1Icon.o: WinSelect1Icon.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinSelect1Item.o: WinSelect1Item.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinSelect1Line.o: WinSelect1Line.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinShopEditor.o: WinShopEditor.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

WinTitle.o: WinTitle.cpp \
		win.h \
		WinTitle.h \
		include/curses.h \
		Windows.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		Config.h \
		File.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h

Windows.o: Windows.cpp \
		Windows.h \
		include/curses.h \
		common.h \
		CString.h \
		msg.h \
		msg.euc \
		Data.h

main.o: main.cpp \
		include/curses.h \
		CString.h \
		main.h \
		Config.h \
		File.h \
		win.h \
		WinTitle.h \
		Windows.h \
		common.h \
		msg.h \
		msg.euc \
		Data.h \
		WinSelect1Icon.h \
		WinSelect1Line.h \
		WinSelect1Item.h \
		WinEditValue.h \
		WinEditValue_Flg.h \
		WinEditValue_Tile.h \
		WinEditValue_Event.h \
		WinEditValue_Pos.h \
		WinEditValue_Cmask.h \
		WinGetPath.h \
		WinMapEditor.h \
		WinMsg.h \
		WinMycharEditor.h \
		WinEnemyEditor.h \
		WinPartyEditor.h \
		WinPGEditor.h \
		WinScenarioEditor.h \
		WinEventEditor.h \
		WinItemEditor.h \
		WinShopEditor.h \
		WinMessageEditor.h \
		Title.h

